version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .envs/auth.env
      - .envs/database.env
      - .envs/logger.env
      - .envs/ml.env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    env_file:
      - .envs/database.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: